### ISSUE TITLE
Including this to the official module list

### ISSUE THREAD

**Issue by benkuper** [nicolaserard/Spat-Revolution-Chataigne-Module#1]
Hello,
would it be possible to change the downloadURL to the downloadable zip file ?
This is the url that it needs to point to : https://github.com/nicolaserard/Spat-Revolution-Chataigne-Module/archive/refs/heads/main.zip
This would allow putting the module in the official list and make it downloadable from Chataigne directly

**Comment by nicolaserard** [comment]
Thanks Ben for pointing it this issue (and sorry for the delay, I didn't see it).. This is now down, is it possible to integrate it to the official list of Chataigne?
